apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "healthcare-app.fullname" . }}-egress
spec:
  podSelector:
    matchLabels:
      app: {{ include "healthcare-app.name" . }}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.aws.dbEgressCidr }}
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
